controller:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/awx/**'
hub:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/hub/**'
eda:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/eda/**'
framework:
  - changed-files:
      - any-glob-to-any-file:
          - 'framework/**'
platform:
  - changed-files:
      - any-glob-to-any-file:
          - 'platform/**'
playwright:
  - changed-files:
      - any-glob-to-any-file:
          - 'playwright/**'
vitest:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - '**/*.spec.ts'
          - '**/*.spec.tsx'
ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
