# https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-parameters/

sonar.projectKey = ansible:ansible_aap-ui
sonar.host = https://localhost:4100
sonar.sources = framework/,frontend/,platform/
sonar.tests = cypress/,playwright/

sonar.cpd.exclusions=frontend/**/*,platform/**/*
