coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        flags:
          - unit-tests
  ignore:
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.spec.ts"
    - "**/*.spec.tsx"
    - "**/vitest.*.ts"
    - "**/webpack.config.cjs"
    - "**/vite.config.ts"
    - "**/interfaces/generated/**"
    - "**/interfaces/generated-from-swagger/**"
    - "**/swagger.json"
    - "**/openapi.json"
    - "**/package-lock.json"

flags:
  unit-tests:
    carryforward: true
  e2e-tests:
    carryforward: true
