coverage:
  status:
    project:
      unit:
        flags:
          - unit-tests
      e2e:
        flags:
          - e2e-tests
        informational: true
  ignore:
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.spec.ts"
    - "**/*.spec.tsx"
    - "**/vitest.setup.ts"
    - "**/webpack.config.cjs"
    - "**/vite.config.ts"
    - "**/interfaces/generated/**"
    - "**/interfaces/generated-from-swagger/**"
    - "**/swagger.json"
    - "**/openapi.json"
    - "**/package-lock.json"
