# https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-parameters/

sonar.projectKey = ansible-automation-platform_aap-ui
sonar.organization = ansible-automation-platform
sonar.sources = framework/,frontend/,platform/
sonar.tests = cypress/,playwright/
sonar.exclusions = **/*.fixture.ts,**/*.fixture.json,**/vite.config.ts
sonar.coverage.exclusions = **/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.cy.ts,**/*.cy.tsx,**/vitest.setup.ts,**/webpack.config.cjs,**/vite.config.ts
sonar.cpd.exclusions=framework/**/*,frontend/**/*,platform/**/*

sonar.javascript.lcov.reportPaths=./coverage/vitest/lcov.info,./coverage/playwright/lcov.info
sonar.typescript.lcov.reportPaths=./coverage/vitest/lcov.info,./coverage/playwright/lcov.info
sonar.coverage.overall_condition=0
sonar.coverage.new_condition=50
