/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaAction {
  id: number;
  rule: { id: number; name: string };
  description?: string;
  activation?: { id: number; name: string };
  type: string;
  status?: string;
  ruleset: { id: number; name: string };
  fired_date?: string;
  rule_definition?: string;
}
