/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaCredential {
  id: number;
  name: string;
  description?: string;
  credential_type: string;
  username: string;
  token: string;
  created_at?: string;
  modified_at?: string;
}
