/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaDecisionEnvironment {
  id: number;
  name: string;
  description: string;
  image_url: string;
  tag: string;
  credential: number;
  created_at: string;
  modified_at: string;
}
