/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaGroup {
  id: number;
  name: string;
  description?: string;
  created_at?: string;
  modified_at?: string;
  roles?: { id: number; name: string }[];
  users?: { id: number; name: string }[];
}
