/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaHost {
  id: string;
  host: string;
  rule: { id: string; name: string };
  ruleset?: { id: string; name: string };
  fired_date?: string;
}
