/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaResult<T> {
  count: number;
  next?: string;
  page?: number;
  page_size?: 20;
  previous?: string;
  results?: T[];
}
