/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaRule {
  id: number;
  name: string;
  description: string;
  action: object;
  project?: { id: string; name: string };
  ruleset?: {
    id: string;
    name: string;
  };
  type: string;
  fired_stats: {
    fired_date: string;
    fire_count: string;
  };
  conditions: string;
  created_at: string;
  modified_at: string;
}
