/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaRuleAudit {
  id: number;
  name?: string;
  description?: string;
  status?: string;
  activation_id?: string;
  activation_name?: string;
  created_at?: string;
  fired_at?: string;
}
