/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaRulebook {
  id: number;
  name: string;
  description: string;
  status?: string;
  ruleset_count: number;
  rule_count: number;
  fire_count: number;
  created_at: string;
  modified_at: string;
  is_enabled: boolean;
  throttle: boolean;
  project: number;
}
