/* tslint:disable */

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface FiredStats {
  fired_count?: number;
  last_fired_at?: string;
  total_type?: string;
  status?: string;
  status_total?: number;
  object_total?: number;
  pct_object_total?: number;
  window_total?: number;
  pct_window_total?: number;
}

export interface EdaRule {
  id: number;
  name: string;
  description: string;
  action: object;
  project?: number;
  ruleset?: number;
  rulebook?: number;
  type: string;
  fired_stats: FiredStats;
  conditions: string;
  created_at: string;
  modified_at: string;
}
