/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

interface FiredStats {
  total_type: string;
  status: string;
  status_total: number;
  object_total: number;
  pct_object_total: number;
  window_total: number;
  pct_window_total: number;
}

export interface EdaRuleset {
  id: number;
  name: string;
  status: string;
  rule_count: number;
  fired_stats: FiredStats;
}
