/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaUser {
  id: number;
  email: string;
  username: string;
  first_name?: string;
  last_name?: string;
  type?: string;
  password: string;
  is_active: boolean;
  is_superuser: boolean;
  is_verified: boolean;
}
