/* tslint:disable */
import { EdaRole } from './EdaRole';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EdaUser {
  id: number;
  email: string;
  username: string;
  first_name?: string;
  last_name?: string;
  password: string;
  roles: EdaRole[];
}

export interface EdaUserIn {
  id: number;
  email: string;
  username: string;
  first_name?: string;
  last_name?: string;
  password: string;
  roles: number[];
}
