/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */

export interface Peer {
  id: number;
  url: string;
  address: string;
  port: number;
  protocol: string;
  websocket_path: string;
  is_internal: boolean;
  canonical: boolean;
  instance: number;
  peers_from_control_nodes: boolean;
  full_address: string;
  name: string;
}
