/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  id: number;
  type: string;
  url: string;
  related: {
    teams: string;
    organizations: string;
    admin_of_organizations: string;
    projects: string;
    credentials: string;
    roles: string;
    activity_stream: string;
    access_list: string;
    tokens: string;
    authorized_tokens: string;
    personal_tokens: string;
  };
  summary_fields: {
    user_capabilities: {
      edit: boolean;
      delete: boolean;
    };
    indirect_access?: {
      descendant_roles: string[];
      role: {
        id: number;
        name: string;
        description: string;
        user_capabilities: {
          unattach: boolean;
        };
      };
    }[];
  };
  created: string;
  modified: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  is_superuser: boolean;
  is_system_auditor: boolean;
  ldap_dn: string;
  last_login: string;
  external_account: null;
  auth: unknown[];
  password: string;
}
