import { JobTemplate } from '../../../interfaces/JobTemplate';

export const testJobTemplateFixture: JobTemplate = {
  id: 1,
  type: 'job_template',
  url: '/api/v2/job_templates/1/',
  name: 'Test Job Template',
  description: 'Test job template description',
  job_type: 'run',
  inventory: 1,
  project: 1,
  playbook: 'test-playbook.yml',
  scm_branch: 'main',
  forks: 0,
  limit: 'test-limit',
  verbosity: 0,
  extra_vars: '{"key": "value"}',
  job_tags: 'tag1,tag2',
  force_handlers: false,
  skip_tags: 'skip1,skip2',
  start_at_task: '',
  timeout: 0,
  use_fact_cache: false,
  organization: 1,
  diff_mode: false,
  allow_simultaneous: false,
  ask_scm_branch_on_launch: false,
  ask_diff_mode_on_launch: false,
  ask_variables_on_launch: false,
  ask_limit_on_launch: false,
  ask_tags_on_launch: false,
  ask_skip_tags_on_launch: false,
  ask_job_type_on_launch: false,
  ask_verbosity_on_launch: false,
  ask_inventory_on_launch: false,
  ask_credential_on_launch: false,
  ask_execution_environment_on_launch: false,
  ask_labels_on_launch: false,
  ask_forks_on_launch: false,
  ask_job_slice_count_on_launch: false,
  ask_timeout_on_launch: false,
  ask_instance_groups_on_launch: false,
  become_enabled: false,
  webhook_service: 'github',
  webhook_credential: 1,
  host_config_key: '',
  status: 'successful',
  job_slice_count: 1,
  last_job_failed: false,
  last_job_run: '2024-01-01T00:00:00Z',
  next_job_run: '',
  prevent_instance_group_fallback: false,
  survey_enabled: false,
  webhook_url: 'https://example.com/webhook',
  webhook_key: 'test-webhook-key',
  created: '2024-01-01T00:00:00Z',
  modified: '2024-01-02T00:00:00Z',
  related: {
    callback: '/api/v2/job_templates/1/callback/',
    named_url: '/api/v2/job_templates/1/named_url/',
    created_by: '/api/v2/users/1/',
    modified_by: '/api/v2/users/1/',
    labels: '/api/v2/job_templates/1/labels/',
    inventory: '/api/v2/inventories/1/',
    project: '/api/v2/projects/1/',
    organization: '/api/v2/organizations/1/',
    credentials: '/api/v2/job_templates/1/credentials/',
    last_job: '/api/v2/jobs/1/',
    jobs: '/api/v2/job_templates/1/jobs/',
    schedules: '/api/v2/job_templates/1/schedules/',
    activity_stream: '/api/v2/job_templates/1/activity_stream/',
    launch: '/api/v2/job_templates/1/launch/',
    webhook_key: '/api/v2/job_templates/1/webhook_key/',
    webhook_receiver: '/api/v2/job_templates/1/github/',
    notification_templates_started: '/api/v2/job_templates/1/notification_templates_started/',
    notification_templates_success: '/api/v2/job_templates/1/notification_templates_success/',
    notification_templates_error: '/api/v2/job_templates/1/notification_templates_error/',
    access_list: '/api/v2/job_templates/1/access_list/',
    survey_spec: '/api/v2/job_templates/1/survey_spec/',
    object_roles: '/api/v2/job_templates/1/object_roles/',
    instance_groups: '/api/v2/job_templates/1/instance_groups/',
    slice_workflow_jobs: '/api/v2/job_templates/1/slice_workflow_jobs/',
    copy: '/api/v2/job_templates/1/copy/',
  },
  summary_fields: {
    organization: { id: 1, name: 'Test Organization', description: '' },
    inventory: {
      id: 1,
      name: 'Test Inventory',
      description: '',
      has_active_failures: false,
      total_hosts: 10,
      hosts_with_active_failures: 0,
      total_groups: 5,
      has_inventory_sources: true,
      total_inventory_sources: 2,
      inventory_sources_with_failures: 0,
      organization_id: 1,
      kind: 'standard',
    },
    project: { id: 1, name: 'Test Project' },
    execution_environment: { id: 1, name: 'Test EE' },
    credentials: [{ id: 1, name: 'Test Credential', description: '', kind: 'ssh', cloud: false }],
    labels: {
      count: 1,
      results: [
        {
          id: 1,
          name: 'test-label',
          organization: 1,
          type: 'label',
          url: '/api/v2/labels/1/',
          created: '2024-01-01T00:00:00Z',
          modified: '2024-01-01T00:00:00Z',
          summary_fields: {
            created_by: { username: 'admin', first_name: 'Admin', last_name: 'User', id: 1 },
            modified_by: { username: 'admin', first_name: 'Admin', last_name: 'User', id: 1 },
            organization: { id: 1, name: 'Test Organization', description: '' },
          },
        },
      ],
    },
    recent_jobs: [
      {
        id: 1,
        status: 'successful',
        finished: '2024-01-01T00:00:00Z',
        canceled_on: '',
        type: 'job',
      },
      { id: 2, status: 'failed', finished: '2024-01-02T00:00:00Z', canceled_on: '', type: 'job' },
    ],
    created_by: { id: 1, username: 'admin', first_name: 'Admin', last_name: 'User' },
    modified_by: { id: 1, username: 'admin', first_name: 'Admin', last_name: 'User' },
    webhook_credential: {
      id: 1,
      name: 'GitHub Webhook',
      description: '',
      kind: 'github',
      cloud: false,
    },
    last_job: {
      id: 1,
      name: 'Test Job',
      description: '',
      finished: '2024-01-01T00:00:00Z',
      status: 'successful',
      failed: false,
    },
    last_update: {
      id: 1,
      name: 'Test Update',
      description: '',
      status: 'successful',
      failed: false,
    },
    object_roles: {
      admin_role: { description: 'Admin', name: 'Admin', id: 1 },
      execute_role: { description: 'Execute', name: 'Execute', id: 2 },
      read_role: { description: 'Read', name: 'Read', id: 3 },
    },
    user_capabilities: {
      edit: true,
      delete: true,
      start: true,
      schedule: true,
      copy: true,
    },
    resolved_environment: {
      id: 1,
      name: 'Test EE',
      description: '',
      image: 'test-image:latest',
    },
  },
};
