x-environment:
  &eda-env
  - EDA_DB_HOST=eda-postgres
  - EDA_MQ_HOST=eda-redis
  - DJANGO_SETTINGS_MODULE=aap_eda.settings.default
  - EDA_DB_PASSWORD=secret
  - EDA_SECRET_KEY=secret
  - EDA_ALLOWED_HOSTS=['*']
  - DJANGO_SUPERUSER_USERNAME=testuser
  - DJANGO_SUPERUSER_PASSWORD=testpass
  - DJANGO_SUPERUSER_EMAIL=admin@example.com

services:
  eda-server:
    container_name: eda-server
    image: quay.io/ansible/eda-server:main
    environment: *eda-env
    command:
      - /bin/bash
      - -c
      - aap-eda-manage migrate && aap-eda-manage createsuperuser --noinput || true && aap-eda-manage runserver 0.0.0.0:8000
    ports: 
    - 8000:8000
    depends_on:
      eda-redis:
        condition: service_healthy
      eda-postgres:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '-q', 'http://localhost:8000/_healthz' ]
      interval: 5s

  eda-worker:
    container_name: eda-worker
    image: quay.io/ansible/eda-server:main 
    environment: *eda-env
    command: aap-eda-manage rqworker --worker-class aap_eda.core.tasking.Worker
    depends_on:
      eda-server:
        condition: service_healthy
      eda-redis:
        condition: service_healthy
      eda-postgres:
        condition: service_healthy

  eda-postgres:
    container_name: eda-postgres
    image: docker.io/library/postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eda
    ports:
      - 5432:5432
    # volumes:
      # - eda-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 5s

  eda-redis:
    container_name: eda-redis
    image: docker.io/library/redis:7
    ports:
      - 6379:6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s

# volumes:
#   eda-postgres: {}
