export type HubSettings = {
  GALAXY_AUTO_SIGN_COLLECTIONS: boolean;
  GALAXY_COLLECTION_SIGNING_SERVICE: string;
  GALAXY_CONTAINER_SIGNING_SERVICE: string;
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS: boolean;
  GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD: boolean;
  GALAXY_MINIMUM_PASSWORD_LENGTH: number | null;
  GALAXY_REQUIRE_CONTENT_APPROVAL: boolean;
  GALAXY_REQUIRE_SIGNATURE_FOR_APPROVAL: boolean;
  GALAXY_SIGNATURE_UPLOAD_ENABLED: boolean;
  GALAXY_TOKEN_EXPIRATION: number | null;
};
