export enum EdaRoute {
  Eda = 'eda',

  Overview = 'eda-overview',

  RuleAudits = 'eda-rule-audits',
  RuleAuditPage = 'eda-rule-audit-page',
  RuleAuditDetails = 'eda-rule-audit-details',
  RuleAuditActions = 'eda-rule-audit-actions',
  RuleAuditEvents = 'eda-rule-audit-events',

  RulebookActivations = 'eda-rulebook-activations',
  CreateRulebookActivation = 'eda-create-rulebook-activation',
  RulebookActivationPage = 'eda-rulebook-activation-page',
  RulebookActivationDetails = 'eda-rulebook-activation-details',
  RulebookActivationHistory = 'eda-rulebook-activation-history',
  RulebookActivationInstancePage = 'eda-rulebook-activation-instance-page',
  RulebookActivationInstanceDetails = 'eda-rulebook-activation-instance-details',
  RulebookActivationTeamAccess = 'eda-rulebook-activation-team-access',
  RulebookActivationUserAccess = 'eda-rulebook-activation-user-access',
  RulebookActivationAddTeams = 'eda-rulebook-activation-add-teams',
  RulebookActivationAddUsers = 'eda-rulebook-activation-add-users',

  Projects = 'eda-projects',
  CreateProject = 'eda-create-project',
  EditProject = 'eda-edit-project',
  ProjectPage = 'eda-project-page',
  ProjectDetails = 'eda-project-details',
  ProjectTeamAccess = 'eda-project-project-team-access',
  ProjectUserAccess = 'eda-project-project-user-access',
  ProjectAddUsers = 'eda-project-add-users',
  ProjectAddTeams = 'eda-project-add-teams',

  DecisionEnvironments = 'eda-decision-environments',
  CreateDecisionEnvironment = 'eda-create-decision-environment',
  EditDecisionEnvironment = 'eda-edit-decision-environment',
  DecisionEnvironmentPage = 'eda-decision-environment-page',
  DecisionEnvironmentDetails = 'eda-decision-environment-details',
  DecisionEnvironmentTeamAccess = 'eda-decision-environments-team-access',
  DecisionEnvironmentUserAccess = 'eda-decision-environments-user-access',
  DecisionEnvironmentAddTeams = 'eda-decision-environments-add-teams',
  DecisionEnvironmentAddUsers = 'eda-decision-environments-add-users',

  Credentials = 'eda-credentials',
  CreateCredential = 'eda-create-credential',
  EditCredential = 'eda-edit-credential',
  CredentialPage = 'eda-credential-page',
  CredentialDetails = 'eda-credential-details',
  CredentialTeamAccess = 'eda-credential-team-access',
  CredentialUserAccess = 'eda-credential-user-access',
  CredentialAddTeams = 'eda-credential-add-teams',
  CredentialAddUsers = 'eda-credential-add-users',

  CredentialTypes = 'eda-credential-types',
  CreateCredentialType = 'eda-create-credential-type',
  EditCredentialType = 'eda-edit-credential-type',
  CredentialTypePage = 'eda-credential-type-page',
  CredentialTypeDetails = 'eda-credential-type-details',
  CredentialTypeCredentials = 'eda-credential-type-credentials',
  CredentialTypeTeamAccess = 'eda-credential-type-team-access',
  CredentialTypeUserAccess = 'eda-credential-type-user-access',
  CredentialTypeAddTeams = 'eda-credential-type-add-teams',
  CredentialTypeAddUsers = 'eda-credential-type-add-users',

  EventStreams = 'eda-event-streams',
  CreateEventStream = 'eda-create-event-stream',
  EventStreamPage = 'eda-event-stream-page',
  EventStreamDetails = 'eda-event-stream-details',
  EventStreamHistory = 'eda-event-stream-history',
  EventStreamInstancePage = 'eda-event-stream-instance-page',
  EventStreamInstanceDetails = 'eda-event-stream-instance-details',

  Access = 'eda-access',
  Users = 'eda-users',
  CreateUser = 'eda-create-user',
  EditUser = 'eda-edit-user',
  EditCurrentUser = 'eda-edit-current-user',
  UserPage = 'eda-user-page',
  MyPage = 'eda-me-page',
  MyDetails = 'eda-my-details',
  MyTokens = 'eda-my-tokens',
  UserDetails = 'eda-user-details',
  UserTokens = 'eda-user-tokens',
  UserRoles = 'eda-user-roles',
  UserAddRoles = 'eda-user-add-roles',

  Organizations = 'eda-organizations',
  CreateOrganization = 'eda-create-organization',
  EditOrganization = 'eda-edit-organization',
  OrganizationPage = 'eda-organization-page',
  OrganizationDetails = 'eda-organization-details',

  Roles = 'eda-roles',
  CreateRole = 'eda-create-role',
  EditRole = 'eda-edit-role',
  RolePage = 'eda-role-page',
  RoleDetails = 'eda-role-details',

  CreateControllerToken = 'eda-create-controller-token',

  Webhooks = 'eda-webhooks',
  CreateWebhook = 'eda-create-webhook',
  EditWebhook = 'eda-edit-webhook',
  WebhookPage = 'eda-webhook-page',
  WebhookDetails = 'eda-webhook-details',

  Settings = 'eda-settings',
  SettingsPreferences = 'eda-settings-preferences',

  Login = 'eda-login',
}
