export enum PlatformRoute {
  Login = 'platform-login',
  Dashboard = 'platform-dashboard',
  AWX = 'platform-awx',
  HUB = 'platform-hub',
  EDA = 'platform-eda',
  Root = 'platform-root',
  Users = 'platform-users',
  UserPage = 'platform-user-page',
  UserDetails = 'platform-user-details',
  CreateUser = 'platform-create-user',
  EditUser = 'platform-edit-user',
  UserTeams = 'platform-user-teams',
  Teams = 'platform-teams',
  TeamPage = 'platform-team-page',
  TeamDetails = 'platform-team-details',
  CreateTeam = 'platform-create-team',
  EditTeam = 'platform-edit-team',
  TeamUsers = 'platform-team-users',
  Organizations = 'platform-organizations',
  OrganizationPage = 'platform-organization-page',
  OrganizationDetails = 'platform-organization-details',
  CreateOrganization = 'platform-create-organization',
  EditOrganization = 'platform-edit-organization',
}
