import { UnifiedJob } from '../../interfaces/UnifiedJob';

export const jobsFixture: {
  count: number;
  next: string | null;
  previous: string | null;
  results: UnifiedJob[];
} = {
  count: 310,
  next: '/api/v2/unified_jobs/?not__launch_type=sync&order_by=-finished&page=2&page_size=10',
  previous: null,
  results: [
    {
      id: 491,
      type: 'workflow_job',
      url: '/api/v2/workflow_jobs/491/',
      related: {
        created_by: '/api/v2/users/2/',
        modified_by: '/api/v2/users/2/',
        unified_job_template: '/api/v2/workflow_job_templates/63/',
        workflow_job_template: '/api/v2/workflow_job_templates/63/',
        notifications: '/api/v2/workflow_jobs/491/notifications/',
        workflow_nodes: '/api/v2/workflow_jobs/491/workflow_nodes/',
        labels: '/api/v2/workflow_jobs/491/labels/',
        activity_stream: '/api/v2/workflow_jobs/491/activity_stream/',
        relaunch: '/api/v2/workflow_jobs/491/relaunch/',
        cancel: '/api/v2/workflow_jobs/491/cancel/',
      },
      summary_fields: {
        inventory: {
          id: 1,
          name: 'Demo Inventory',
          description: '',
          has_active_failures: false,
          total_hosts: 1,
          hosts_with_active_failures: 0,
          total_groups: 0,
          has_inventory_sources: true,
          total_inventory_sources: 1,
          inventory_sources_with_failures: 1,
          organization_id: 1,
          kind: '',
        },
        workflow_job_template: { id: 63, name: 'Workflow 1214', description: '' },
        unified_job_template: {
          id: 63,
          name: 'Workflow 1214',
          description: '',
          unified_job_type: 'workflow_job',
        },
        created_by: { id: 2, username: 'vnambiar', first_name: '', last_name: '' },
        modified_by: { id: 2, username: 'vnambiar', first_name: '', last_name: '' },
        user_capabilities: { delete: true, start: true },
        labels: { count: 0, results: [] },
      },
      created: '2022-12-14T17:13:12.934884Z',
      modified: '2022-12-14T17:13:13.401795Z',
      name: 'Workflow1214',
      description: '',
      unified_job_template: 63,
      launch_type: 'manual',
      status: 'failed',
      failed: true,
      started: '2022-12-14T17:13:13.385572Z',
      finished: '2022-12-14T17:13:21.660217Z',
      canceled_on: null,
      elapsed: 8.275,
      job_explanation: 'No error handling paths found, marking workflow as failed',
      launched_by: { id: 2, name: 'vnambiar', type: 'user', url: '/api/v2/users/2/' },
      work_unit_id: null,
    } as unknown as UnifiedJob,
    {
      id: 492,
      type: 'job',
      url: '/api/v2/jobs/492/',
      name: 'Test1214',
      status: 'running',
      failed: false,
      started: '2022-12-13T15:37:33.593820Z',
      finished: '2022-12-13T15:37:45.846569Z',
      summary_fields: {
        job_template: { id: 62, name: 'Test 1214', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 489,
      type: 'job',
      url: '/api/v2/jobs/489/',
      name: 'Demo Job Template',
      status: 'running',
      failed: false,
      started: '2022-12-13T15:37:33.593820Z',
      finished: null,
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 488,
      type: 'job',
      url: '/api/v2/jobs/488/',
      name: 'DemoJobTemplate',
      status: 'successful',
      failed: false,
      started: '2022-12-12T20:48:28.230067Z',
      finished: '2022-12-12T20:48:34.222172Z',
      summary_fields: {
        job_template: { id: 7, name: 'DemoJobTemplate', description: '' },
        user_capabilities: { delete: false, start: true },
      },
    } as UnifiedJob,
    {
      id: 487,
      type: 'job',
      url: '/api/v2/jobs/487/',
      name: 'Demo Job Template',
      status: 'running',
      failed: false,
      started: '2022-12-12T20:43:51.685714Z',
      finished: '2022-12-12T20:43:57.789392Z',
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: false },
      },
    } as UnifiedJob,
    {
      id: 486,
      type: 'job',
      url: '/api/v2/jobs/486/',
      name: 'Demo Job Template',
      status: 'successful',
      failed: false,
      started: '2022-12-12T20:42:48.373704Z',
      finished: '2022-12-12T20:42:55.708997Z',
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 485,
      type: 'job',
      url: '/api/v2/jobs/485/',
      name: 'Demo Job Template',
      status: 'successful',
      failed: false,
      started: '2022-12-12T20:42:13.118425Z',
      finished: '2022-12-12T20:42:19.100247Z',
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 484,
      type: 'job',
      url: '/api/v2/jobs/484/',
      name: 'Demo Job Template',
      status: 'successful',
      failed: false,
      started: '2022-12-12T20:41:57.461967Z',
      finished: '2022-12-12T20:42:04.005750Z',
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 483,
      type: 'job',
      url: '/api/v2/jobs/483/',
      name: 'Demo Job Template',
      status: 'successful',
      failed: false,
      started: '2022-12-12T20:40:36.112046Z',
      finished: '2022-12-12T20:40:41.855997Z',
      summary_fields: {
        job_template: { id: 7, name: 'Demo Job Template', description: '' },
        user_capabilities: { delete: true, start: true },
      },
    } as unknown as UnifiedJob,
    {
      id: 490,
      type: 'system_job',
      url: '/api/v2/system_jobs/490/',
      name: 'Cleanup Activity Stream',
      description: 'Remove activity stream history',
      status: 'successful',
      failed: false,
      started: '2022-12-13T20:39:07.198954Z',
      finished: '2022-12-13T20:39:12.465023Z',
      summary_fields: {
        system_job_template: {
          id: 2,
          name: 'Cleanup Activity Stream',
          description: 'Remove activity stream history',
        },
        user_capabilities: { delete: true, start: false },
      },
    } as unknown as UnifiedJob,
  ],
};
