import { renderHook } from '@testing-library/react';
import { describe, expect, test, vi } from 'vitest';
import { useGetLaunchedByDetails } from './jobUtils';
import { UnifiedJob } from '../../interfaces/UnifiedJob';

const mockGetPageUrl = vi.fn((route: string, options?: { params?: Record<string, number> }) => {
  const params = options?.params;
  if (!params) return route;
  return `${route}/${Object.values(params).join('/')}`;
});

const mockT = vi.fn((key: string) => {
  if (key === 'Generated by Ansible Automation Platform') {
    return 'Generated by Ansible Automation Platform';
  }
  return key;
});

vi.mock('@ansible/ansible-ui-framework/PageNavigation/useGetPageUrl', () => ({
  useGetPageUrl: () => mockGetPageUrl,
}));

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: mockT,
  }),
}));

describe('useGetLaunchedByDetails', () => {
  describe('dependency launch type', () => {
    test('should return launched_by name when present', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'dependency',
        launched_by: {
          id: 123,
          name: 'Dependency Job',
          type: 'job',
          url: '/api/v2/jobs/123/',
        },
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('Dependency Job');
      expect(launchedBy.link).toBe('');
    });

    test('should return empty string when launched_by name is missing', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'dependency',
        launched_by: {
          id: 123,
          name: '',
          type: 'job',
          url: '/api/v2/jobs/123/',
        },
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('');
      expect(launchedBy.link).toBe('');
    });

    test('should translate "Generated by AWX" to "Generated by Ansible Automation Platform"', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'dependency',
        launched_by: {
          id: 123,
          name: 'Generated by AWX',
          type: 'job',
          url: '/api/v2/jobs/123/',
        },
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('Generated by Ansible Automation Platform');
      expect(launchedBy.link).toBe('');
      expect(mockT).toHaveBeenCalledWith('Generated by Ansible Automation Platform');
    });

    test('should return empty object when launched_by is undefined and no other fields', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'dependency',
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy).toEqual({});
    });
  });

  describe('manual launch type', () => {
    test('should return username and user link', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'manual',
        summary_fields: {
          user_capabilities: { delete: true, start: true },
          created_by: {
            id: 1,
            username: 'admin',
            first_name: 'Admin',
            last_name: 'User',
          },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('admin');
      expect(launchedBy.link).toContain('1');
    });
  });

  describe('scheduled launch type', () => {
    test('should return schedule name and schedule link', () => {
      const job: Partial<UnifiedJob> = {
        type: 'job',
        launch_type: 'scheduled',
        summary_fields: {
          user_capabilities: { delete: true, start: true },
          unified_job_template: {
            id: 100,
            name: 'My Template',
            description: 'Template description',
            unified_job_type: 'job',
          },
          schedule: {
            id: 5,
            name: 'Daily Schedule',
            description: 'Daily schedule description',
            next_run: '2024-01-01T00:00:00Z',
          },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('Daily Schedule');
      expect(launchedBy.link).toContain('100');
      expect(launchedBy.link).toContain('5');
    });
  });

  describe('webhook launch type', () => {
    test('should return Webhook and job template link', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'webhook',
        summary_fields: {
          user_capabilities: { delete: true, start: true },
          created_by: {
            id: 1,
            username: 'admin',
            first_name: 'Admin',
            last_name: 'User',
          },
          job_template: {
            id: 10,
            name: 'My Template',
            description: 'Template description',
          },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('Webhook');
      expect(launchedBy.link).toContain('10');
    });

    test('should return Webhook and workflow template link', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'webhook',
        summary_fields: {
          user_capabilities: { delete: true, start: true },
          created_by: {
            id: 1,
            username: 'admin',
            first_name: 'Admin',
            last_name: 'User',
          },
          workflow_job_template: {
            id: 15,
            name: 'My Workflow',
            description: 'Workflow description',
          },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy.value).toBe('Webhook');
      expect(launchedBy.link).toContain('15');
    });
  });

  describe('early return conditions', () => {
    test('should return empty object when no created_by, schedule, or launched_by', () => {
      const job: Partial<UnifiedJob> = {
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy).toEqual({});
    });

    test('should not return empty when only launched_by exists', () => {
      const job: Partial<UnifiedJob> = {
        launch_type: 'dependency',
        launched_by: {
          id: 123,
          name: 'Some Job',
          type: 'job',
          url: '/api/v2/jobs/123/',
        },
        summary_fields: {
          user_capabilities: { delete: true, start: true },
        },
      };

      const { result } = renderHook(() => useGetLaunchedByDetails());
      const launchedBy = result.current(job as UnifiedJob);

      expect(launchedBy).not.toEqual({});
      expect(launchedBy.value).toBe('Some Job');
    });
  });
});
