import { WorkflowJobTemplate } from '../../../interfaces/WorkflowJobTemplate';

export const testWorkflowJobTemplateFixture: WorkflowJobTemplate = {
  id: 1,
  type: 'workflow_job_template',
  url: '/api/v2/workflow_job_templates/1/',
  name: 'Test Workflow Job Template',
  description: 'Test workflow description',
  organization: 1,
  inventory: 1,
  scm_branch: 'main',
  limit: 'test-limit',
  extra_vars: '{"key": "value"}',
  job_tags: 'tag1,tag2',
  skip_tags: 'skip1,skip2',
  allow_simultaneous: false,
  survey_enabled: false,
  webhook_service: 'github',
  webhook_credential: 1,
  ask_inventory_on_launch: false,
  ask_scm_branch_on_launch: false,
  ask_limit_on_launch: false,
  ask_labels_on_launch: false,
  ask_skip_tags_on_launch: false,
  ask_tags_on_launch: false,
  ask_variables_on_launch: false,
  created: '2024-01-01T00:00:00Z',
  modified: '2024-01-02T00:00:00Z',
  last_job_run: '2024-01-01T00:00:00Z',
  last_job_failed: false,
  next_job_run: null,
  status: 'successful',
  related: {
    schedules: '/api/v2/workflow_job_templates/1/schedules/',
    survey_spec: '/api/v2/workflow_job_templates/1/survey_spec/',
    webhook_receiver: '/api/v2/workflow_job_templates/1/github/',
    webhook_key: '/api/v2/workflow_job_templates/1/webhook_key/',
    labels: '/api/v2/workflow_job_templates/1/labels/',
    launch: '/api/v2/workflow_job_templates/1/launch/',
  },
  summary_fields: {
    organization: { id: 1, name: 'Test Organization', description: '' },
    inventory: {
      id: 1,
      name: 'Test Inventory',
      description: '',
      has_active_failures: false,
      total_hosts: 10,
      hosts_with_active_failures: 0,
      total_groups: 5,
      has_inventory_sources: true,
      total_inventory_sources: 2,
      inventory_sources_with_failures: 0,
      organization_id: 1,
      kind: '',
    },
    project: { id: 1, name: 'Test Project' },
    labels: { count: 1, results: [{ id: 1, name: 'test-label' }] },
    recent_jobs: [
      { id: 1, status: 'successful', finished: null, canceled_on: null, type: 'workflow_job' },
      { id: 2, status: 'failed', finished: null, canceled_on: null, type: 'workflow_job' },
    ],
    created_by: { id: 1, username: 'admin', first_name: 'Admin', last_name: 'User' },
    modified_by: { id: 1, username: 'admin', first_name: 'Admin', last_name: 'User' },
    webhook_credential: {
      id: 1,
      name: 'GitHub Webhook',
      description: '',
      kind: 'github',
      cloud: false,
    },
    object_roles: {
      execute_role: { description: 'Execute', name: 'Execute', id: 1 },
      read_role: { description: 'Read', name: 'Read', id: 2 },
      approval_role: { description: 'Approval', name: 'Approval', id: 3 },
      admin_role: { description: 'Admin', name: 'Admin', id: 4 },
    },
    user_capabilities: {
      edit: true,
      delete: true,
      start: true,
      schedule: true,
      copy: true,
    },
    credentials: [],
  },
};
