---
# Basic rulebook with job template,
# to be used with https://github.com/Alex-Izquierdo/eda-awx-project-sample
- name: Basic short
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 10
        delay: 0.5
  rules:
    - name: Run JT at 8
      condition: event.i == 8
      actions:
        - run_job_template:
            organization: Default
            name: run_basic
            job_args:
              extra_vars:
                fake_execution_time: '5'

        - debug:
            msg: 'Basic short rulebook, event {{ event.i }}'
