name: awx-update-server

on:
  workflow_dispatch:
    inputs:
      AWX_SERVER:
        type: string
        required: true
        description: 'AWX Server to update'

jobs:
  # awx-e2e:
  #   uses: ansible/ansible-ui/.github/workflows/awx-e2e.yml@main
  #   with:
  #     AWX_SERVER: ${{ inputs.AWX_SERVER }}
  #   secrets:
  #     AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
  #     CYPRESS_AUI_AWX_E2E_PROJECT_ID: ${{ secrets.CYPRESS_AUI_AWX_E2E_PROJECT_ID }}
  #     CYPRESS_AUI_AWX_E2E_RECORD_KEY: ${{ secrets.CYPRESS_AUI_AWX_E2E_RECORD_KEY }}

  awx-update-server:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/ansible/ansible-ui/actions/variables/AAA" \
          -d '{"name":"AAA","value":"${{ inputs.AWX_SERVER }}"}'          