name: awx-update-server

on:
  workflow_dispatch:
    inputs:
      AWX_SERVER:
        type: string
        required: true
        description: 'AWX Server to update'

jobs:
  awx-e2e:
    name: AWX E2E
    uses: ./.github/workflows/awx-e2e.yml
    with:
      AWX_SERVER: ${{ inputs.AWX_SERVER }}
    secrets:
      AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
      CYPRESS_AUI_AWX_E2E_PROJECT_ID: ${{ secrets.CYPRESS_AUI_AWX_E2E_PROJECT_ID }}
      CYPRESS_AUI_AWX_E2E_RECORD_KEY: ${{ secrets.CYPRESS_AUI_AWX_E2E_RECORD_KEY }}

  awx-update-server:
    name: AWX Update Server
    needs: awx-e2e
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L -X PATCH -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/ansible/ansible-ui/actions/variables/AWX_SERVER" \
          -d '{"name":"AWX_SERVER","value":"${{ inputs.AWX_SERVER }}"}'

      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      #     channel-id: 'CHANNEL_ID,ANOTHER_CHANNEL_ID'
      #     # For posting a simple plain text message
      #     slack-message: "AWX_SERVER: ${{ inputs.AWX_SERVER }}"
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}