name: Component

on:
  workflow_call:
    inputs:
      directory:
        description: 'The base directory to search for .cy.tsx files'
        required: true
        type: string
      generate_junit_results:
        type: boolean
        required: false
        default: false

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate matrix
        id: set-matrix
        run: |
          BASE_DIR="${{ inputs.directory }}"
          matrix=$(find "$BASE_DIR" -type f -name '*.cy.tsx' -exec dirname {} \; | sed "s|^$BASE_DIR/||" | awk -F'/' '{print $1}' | sort -u | jq -R . | jq -s -c .)
          echo "Matrix value: $matrix"
          echo "MATRIX=$matrix" >> $GITHUB_OUTPUT

  component:
    name: Component
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.generate-matrix.outputs.MATRIX) }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: PreCache
        run: npm version 0.0.0 --no-git-tag-version

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Temporarily hide Currents config to bypass Cypress blocking
        run: |
          if [ -f "currents.config.ts" ]; then
            mv currents.config.ts foo.config.ts.backup
          fi

      - name: Cypress
        if: ${{ !inputs.generate_junit_results }}
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          spec: ${{ inputs.directory }}/${{ matrix.directory }}/**/*.cy.tsx
          publish-summary: false
        env:
          CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 300000

      - name: Custom Cypress to generate junit results
        if: ${{ inputs.generate_junit_results }}
        uses: cypress-io/github-action@v6
        with:
          command: npm run component:junit-results -- --spec ./${{ inputs.directory }}/${{ matrix.directory }}/**/*.cy.tsx
          publish-summary: false
        env:
          install: false
          CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 300000

      - name: Restore Currents config after Cypress tests
        if: always()
        run: |
          if [ -f "foo.config.ts.backup" ]; then
            mv foo.config.ts.backup currents.config.ts
          fi

      - name: Compose directory name for jUnit results
        if: ${{ inputs.generate_junit_results }}
        env:
          TEST_DIR: "${{ inputs.directory }}-${{ matrix.directory }}"
        run: |
          TEST_DIR=${{ env.TEST_DIR }}
          TEST_DIR=${TEST_DIR/\//-}
          echo TEST_DIR=${TEST_DIR} >> $GITHUB_ENV

      - name: Upload jUnit results
        if: ${{ inputs.generate_junit_results }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-results-${{ env.TEST_DIR }}
          path: cypress/junit-results/*

      - name: Sanitize directory name
        run: |
          echo "INPUT_DIR=${{ inputs.directory }}" | sed 's|/|_|g' >> $GITHUB_ENV
          echo "MATRIX_DIR=${{ matrix.directory }}" | sed 's|/|_|g' >> $GITHUB_ENV
  
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-${{ env.INPUT_DIR }}-${{ env.MATRIX_DIR }}
          path: cypress/screenshots
          retention-days: 5
          overwrite: true
          if-no-files-found: ignore
    