name: Repository Dispatch

on:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Sync
        run: |
          git fetch https://github.com/ansible/ansible-ui.git main
          git merge --no-ff FETCH_HEAD -m "Merge from upstream"
          git push origin main
