name: Publish Framework

on:
  push:
    tags:
      - '*'

jobs:
  publish-framework:
    name: Publish Framework
    if: github.repository == 'ansible/aap-ui'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf package-lock.json
          rm -rf node_modules
          npm i

      - name: Publish Framework
        working-directory: ./framework
        run: |
          npm run build
          cp -f ../LICENSE.md ./publish/LICENSE.md
          cp -f ./README.md ./publish/README.md
          VERSION=`cat ../package.json | jq -r '.version'` && cat ./publish/package.json | jq --arg version $VERSION '. +{version: $version}' > ./publish/package.json
          cd publish && npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
