name: Platform Update E2E Server

on:
  workflow_dispatch:
    inputs:
      PLATFORM_SERVER:
        type: string
        required: true
        description: 'Platform Server'
      UPDATE_SERVER:
        type: boolean
        required: true
        default: false
        description: 'Update server on success'


jobs:
  platform-e2e:
    name: Platform E2E
    needs: setup
    uses: ./.github/workflows/ds-platform-e2e.yml
    with:
      PLATFORM_SERVER: ${{ github.event.inputs.PLATFORM_SERVER }}
    secrets:
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
      PLATFORM_PROJECT_ID: ${{ secrets.PLATFORM_PROJECT_ID }}
      PLATFORM_RECORD_KEY: ${{ secrets.PLATFORM_RECORD_KEY }}

  platform-update-server:
    name: Platform Update Server
    if: ${{ github.event.inputs.UPDATE_SERVER == 'true' }}
    needs:
      - platform-e2e
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Update Server Variable
        run: |
          curl -f -L -X PATCH -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/variables/PLATFORM_SERVER" \
          -d '{"name":"PLATFORM_SERVER","value":"${{ github.event.inputs.PLATFORM_SERVER }}"}'
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments":
                [
                  {
                    "color": "#00DD00",
                    "blocks":
                      [
                        {
                          "type": "section",
                          "text":
                            {
                              "type": "mrkdwn",
                              "text": "*AAP-UI E2E Server Updated* - <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Success> - <${{ github.event.inputs.PLATFORM_SERVER }}|Server>"
                            }
                        }
                      ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  slack-failure-notification:
    name: Slack Failure Notification
    if: ${{ failure() && needs.setup.outputs.UPDATE_SERVER == 'true' }}
    needs:
      - platform-update-server
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments":
                [
                  {
                    "color": "#FF0000",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "*AAP-UI E2E Server Update Failed* - *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Failure>* - <${{ github.event.inputs.PLATFORM_SERVER }}|Server>"
                        }
                      }
                    ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK