name: Sync

on:
  repository_dispatch:
    types: [sync]

concurrency: merge-main

jobs:
  sync:
    name: Merge Upstream Main to Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Merge Upstream Main to Main
        run: |
          git fetch https://github.com/ansible/ansible-ui.git main
          git merge --no-ff FETCH_HEAD -m "Merge from upstream"
          git push origin main

  slack-failure-notification:
    name: Slack Failure Notification
    if: failure()
    needs:
      - sync
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments":
                [
                  {
                    "color": "#FF0000",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "*Upstream Sync Failure*"
                        }
                      }
                    ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK          