name: Platform E2E

on:
  workflow_call:
    inputs:
      PLATFORM_SERVER:
        type: string
        required: true
      SKIP_JOB:
        type: boolean
        required: false
        default: false
      TAGS:
        type: string
        required: false
    secrets:
      PLATFORM_PASSWORD:
        required: true
      PLATFORM_PROJECT_ID:
        required: true
      PLATFORM_RECORD_KEY:
        required: true

jobs:
  platform-ui-image:
    name: Platform UI Image
    uses: ./.github/workflows/image.yml
    with:
      build-directory: platform
      docker-file: platform/Dockerfile
      docker-target: platform-ui
      docker-image: platform-ui
      upload-image: true

  platform-e2e:
    name: Platform E2E
    runs-on: ubuntu-latest
    needs: platform-ui-image
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
    steps:
      - name: Download container image
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/download-artifact@v4
        with:
          name: platform-ui.tar
      - name: Load container image
        if: ${{ !inputs.SKIP_JOB }}
        run: docker load --input platform-ui.tar
      - name: Checkout
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup node
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PreCache
        if: ${{ !inputs.SKIP_JOB }}
        run: npm version 0.0.0 --no-git-tag-version
      - name: Cache dependencies
        if: ${{ !inputs.SKIP_JOB }}
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' && !inputs.SKIP_JOB
        run: npm ci
      # galaxykit needs pip 23+, Ubuntu 22.04's default Python uses pip 22
      - name: "Install python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install galaxykit
        run: |
          # pip3 install ansible galaxykit
          # pending a release with https://github.com/ansible/galaxykit/pull/116
          pip3 install ansible git+https://github.com/ansible/galaxykit.git@main
      - name: Cypress
        if: ${{ !inputs.SKIP_JOB }}
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: docker run --rm -p 4100:443 -e PLATFORM_SERVER=${{ inputs.PLATFORM_SERVER }} platform-ui
          wait-on: 'https://localhost:4100'
          record: true
          parallel: true
          # auto-cancel-after-failures: 1
          config-file: cypress.platform.config.ts
          tag: ${{ inputs.TAGS }}
        env:
          PLATFORM_SERVER: ${{ inputs.PLATFORM_SERVER }}
          PLATFORM_USERNAME: e2e
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          CYPRESS_PROJECT_ID: ${{ secrets.PLATFORM_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.PLATFORM_RECORD_KEY }}
          CYPRESS_AWX_API_PREFIX: /api/controller/v2
          CYPRESS_EDA_API_PREFIX: /api/eda/v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          CYPRESS_LABELS: '!upstream'
