name: EDA UI Image

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - '*'

jobs:
  eda-ui-image:
    name: EDA UI Image
    uses: ./.github/workflows/image.yml
    with:
      build-script: build
      build-directory: frontend/eda
      docker-target: eda-ui
      docker-image: quay.io/ansible/eda-ui
      docker-publish: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
