name: Nightly Playwright Browsers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1-5'

jobs:
  platform-ui-image:
    name: Platform UI Image
    uses: ./.github/workflows/image.yml
    with:
      build-directory: platform
      build-script: build
      docker-file: platform/Dockerfile
      docker-context: platform
      docker-target: platform-ui
      docker-image: platform-ui
      upload-artifact: true

  playwright:
    name: Playwright mock
    needs:
      - platform-ui-image
    uses: ./.github/workflows/playwright.yml
    strategy:
      fail-fast: false
      matrix:
        project: 
          - "chromium"
    with:
      PROJECT: mock ${{ matrix.project }}
      NOT_TAGS: "@not_mock"
      BROWSER: ${{ matrix.project }}
      SLACK_NOTIFICATION: true
      SUBFOLDER: nightly
      PARALLEL_TESTS: '1'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}    