name: On Schedule - Upgrade Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '15 20 * * *'

concurrency: upgrade

jobs:
  upgrade-dependencies:
    name: Upgrade Package Dependencies
    if: (github.event_name == 'schedule' && github.repository == 'ansible/ansible-ui') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    timeout-minutes: 110
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm run upgrade
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Upgraded package dependencies [skip ci]
