name: Platform PR

on:
  pull_request:

env:
  IS_GITHUB_ACTION: true

concurrency:
  group: platform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm version 0.0.0 --no-git-tag-version
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  checks:
    name: Checks
    runs-on: ubuntu-latest
    needs: packages
    strategy:
      fail-fast: false
      matrix:
        script:
          - eslint
          - tsc
          - prettier
          - build
          - vitest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: npm version 0.0.0 --no-git-tag-version
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t ${{ matrix.script }} --base=origin/main --head=HEAD --verbose

  component:
    name: Component
    needs: packages
    strategy:
      fail-fast: false
      matrix:
        directory:
          - frontend/awx
          - frontend/eda
          - frontend/hub
          - frontend/common
          - framework
          - platform
    uses: ./.github/workflows/component.yml
    with:
      directory: ${{ matrix.directory }}

  platform-ui-image:
    name: Platform UI Image
    needs: packages
    uses: ./.github/workflows/image.yml
    with:
      build-directory: platform
      build-script: build
      docker-context: platform
      docker-file: platform/Dockerfile
      docker-target: platform-ui
      docker-image: platform-ui
      upload-artifact: true

  playwright:
    name: Playwright
    needs: platform-ui-image
    uses: ./.github/workflows/playwright.yml
    with:
      PARALLEL_TESTS: 2
      NOT_TAGS: "@not_mock"
    secrets:
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}

  success:
    name: Success
    runs-on: ubuntu-latest
    needs:
        - checks
        - playwright
        - component
    if: ${{ always() }}
    steps:
      - name: Success Check
        if: ${{ needs.checks.result == 'success' && needs.playwright.result == 'success' && needs.component.result == 'success' }}
        run: echo "All jobs succeeded"
      - name: Failure or Cancelled
        if: ${{ needs.checks.result != 'success' || needs.playwright.result != 'success' || needs.component.result != 'success' }}
        run: |
          echo "One or more jobs failed or were canceled."
          exit 1
