name: Platform UI Image

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - '*'

jobs:
  platform-ui-image:
    uses: ./.github/workflows/image.yml
    with:
      build-directory: platform
      docker-file: platform/Dockerfile
      docker-target: platform-ui
      docker-image: quay.io/ansible/platform-ui
      docker-publish: true
