name: Playwright

on:
  workflow_call:
    inputs:
      PLATFORM_SERVER:
        type: string
        required: false
        default: 'https://localhost:4100'
      PLATFORM_UI:
        type: string
        required: false
        default: 'https://localhost:4100'
      PLATFORM_USERNAME:
        type: string
        required: false
      PLATFORM_PASSWORD:
        type: string
        required: false
      TAGS: 
        type: string
        required: false
      NOT_TAGS: 
        type: string
        required: false
      PARALLEL_TESTS:
        type: string
        required: false
        default: '2'
      PROJECT:
        type: string
        default: "mock chromium"
      SLACK_NOTIFICATION:
        type: boolean
        required: false
        default: false
      BROWSER:
        type: string
        required: false
        default: chromium
      SUBFOLDER:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: false
      PLATFORM_PASSWORD:
        required: true

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      shardIndex: ${{ steps.matrix.outputs.shardIndex }}
      shardTotal: ${{ steps.matrix.outputs.shardTotal }}
    steps:
      - id: matrix
        run: |
          SHARD_TOTAL=${{ inputs.PARALLEL_TESTS }}
          SHARD_INDEX=$(awk -v n=$SHARD_TOTAL 'BEGIN {printf "["; for (i=1; i<=n; i++) printf (i<n ? i ", " : i ); printf "]"}')
          echo "Generated shard index: [$SHARD_INDEX]"
          echo "shardIndex=$SHARD_INDEX" >> $GITHUB_OUTPUT
          # echo "shardIndex=${{ format('[1, {0}]', inputs.PARALLEL_TESTS) }}" >> $GITHUB_OUTPUT
          echo "shardTotal=${{ format('[{0}]', inputs.PARALLEL_TESTS) }}" >> $GITHUB_OUTPUT

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        shardIndex: ${{ fromJSON(needs.matrix.outputs.shardIndex) }}
        shardTotal: ${{ fromJSON(needs.matrix.outputs.shardTotal) }}

    steps:
    - name: Download image
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      uses: actions/download-artifact@v4
      with:
        name: platform-ui.tar

    - name: Load image
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker load --input platform-ui.tar

    - name: Run container
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker run -d --name platform-ui -p 4100:443 -e PLATFORM_SERVER=${{ inputs.PLATFORM_SERVER }} platform-ui

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: PreCache
      run: npm version 0.0.0 --no-git-tag-version

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          /home/runner/.cache/Cypress
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ inputs.BROWSER }}

    - name: Run Playwright Tests
      working-directory: playwright
      run: npx playwright test --project="${{ inputs.PROJECT }}" --project="global setup" --reporter=blob,line --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      env:
        PLATFORM_UI: ${{ inputs.PLATFORM_UI }}
        PLATFORM_USERNAME: ${{ inputs.PLATFORM_USERNAME != '' && inputs.PLATFORM_USERNAME || 'e2e' }}
        PLATFORM_PASSWORD: ${{ inputs.PLATFORM_PASSWORD != '' && inputs.PLATFORM_PASSWORD || secrets.PLATFORM_PASSWORD }}
        TAGS: ${{ inputs.TAGS }}
        NOT_TAGS: ${{ inputs.NOT_TAGS }}
        AWX_API_PREFIX: '/api/controller/v2'

    - name: Upload Playwright Blob Report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.BROWSER }}-blob-report-${{ matrix.shardIndex }}
        path: playwright/blob-report
        retention-days: 1

    - name: Upload Playwright Test Results to GitHub Actions Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-${{ inputs.BROWSER }}-${{ matrix.shardIndex }}
        path: playwright/test-results
        retention-days: 1
        overwrite: true
        if-no-files-found: ignore

    - name: Stop container
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker stop platform-ui

  playwright-report:
    name: Playwright Report
    if: ${{ !cancelled() }}
    needs: [playwright]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: PreCache
      run: npm version 0.0.0 --no-git-tag-version

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          /home/runner/.cache/Cypress
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: ${{ inputs.BROWSER }}-blob-report-*
        merge-multiple: true

    # - name: Merge into JUint Report
    #   run: npx playwright merge-reports --reporter junit ./all-blob-reports > ${{ inputs.BROWSER }}-junit.xml

    # - name: Upload JUint report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ inputs.BROWSER }}-junit-report
    #     path: ${{ inputs.BROWSER }}-junit.xml
    #     retention-days: 1

    # - name: Test Summary
    #   if: always()
    #   uses: test-summary/action@v2
    #   with:
    #     paths: ${{ inputs.BROWSER }}-junit.xml

    - name: Merge into Allure Report
      run: npx playwright merge-reports --reporter allure-playwright ./all-blob-reports 

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        allure_results: allure-results
        subfolder: ${{ inputs.SUBFOLDER }}
        keep_reports: 50

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

    - name: Add Allure Test Results to PR checks
      if: always() && inputs.SUBFOLDER == 'pull-requests'
      uses: guibranco/github-status-action-v2@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Allure Test Results - Might take a few minutes to update'
          state: ${{ job.status }}
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://fuzzy-waffle-2k2r15q.pages.github.io/${{ inputs.SUBFOLDER }}/${{ github.run_number }}

    - name: Allure Test Results Summary Link - Success
      if: success()
      run: |
        SUMMARY=$'## :white_check_mark: Playwright Success\n[Allure Test Results](https://fuzzy-waffle-2k2r15q.pages.github.io/${{ inputs.SUBFOLDER }}/${{ github.run_number }})\n> Might take a few minutes to update'
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    - name: Allure Test Results Summary Link - Failure
      if: failure()
      run: |
        SUMMARY=$'## :bangbang: Playwright Failure\n[Allure Test Results](https://fuzzy-waffle-2k2r15q.pages.github.io/${{ inputs.SUBFOLDER }}/${{ github.run_number }})\n> Might take a few minutes to update'
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
          
    - uses: mshick/add-pr-comment@v2
      if: always() && inputs.SUBFOLDER == 'pull-requests'
      with:
        message-id: allure-summary
        message: |
          ## Playwright Skipped or Canceled
          No test results available
        message-success: |
          ## :white_check_mark: Playwright Success
          [Allure Test Results](https://fuzzy-waffle-2k2r15q.pages.github.io/${{ inputs.SUBFOLDER }}/${{ github.run_number }})
          > Report webpage might take a few minutes to update
        message-failure: |
          ## :bangbang: Playwright Failure
          [Allure Test Results](https://fuzzy-waffle-2k2r15q.pages.github.io/${{ inputs.SUBFOLDER }}/${{ github.run_number }})
          > Report webpage might take a few minutes to update
        refresh-message-position: true

    - name: Slack Success Notification
      if: ${{ inputs.SLACK_NOTIFICATION == true && success() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":playwright: *Playwright* `${{ inputs.PROJECT }}`: :done-circle-check: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Success>*"
                }
              }
            ]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Slack Failure Notification
      if: ${{ inputs.SLACK_NOTIFICATION == true && failure() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":playwright: *Playwright* `${{ inputs.PROJECT }}`: :failed: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Failure>*"
                }
              }
            ]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
