name: Playwright

on:
  workflow_call:
    inputs:
      PLATFORM_SERVER:
        type: string
        required: false
        default: 'https://localhost:4100'
      PLATFORM_UI:
        type: string
        required: false
        default: 'https://localhost:4100'
      PLATFORM_USERNAME:
        type: string
        required: false
      PLATFORM_PASSWORD:
        type: string
        required: false
      TAGS: 
        type: string
        required: false
      NOT_TAGS: 
        type: string
        required: false
      PARALLEL_TESTS:
        type: string
        required: false
        default: '2'
      PROJECT:
        type: string
        default: "mock chromium"
      SLACK_NOTIFICATION:
        type: boolean
        required: false
        default: false
      BROWSER:
        type: string
        required: false
        default: chromium
    secrets:
      SLACK_WEBHOOK_URL:
        required: false
      PLATFORM_PASSWORD:
        required: true

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      shardIndex: ${{ steps.matrix.outputs.shardIndex }}
      shardTotal: ${{ steps.matrix.outputs.shardTotal }}
    steps:
      - id: matrix
        run: |
          SHARD_TOTAL=${{ inputs.PARALLEL_TESTS }}
          SHARD_INDEX=$(awk -v n=$SHARD_TOTAL 'BEGIN {printf "["; for (i=1; i<=n; i++) printf (i<n ? i ", " : i ); printf "]"}')
          echo "Generated shard index: [$SHARD_INDEX]"
          echo "shardIndex=$SHARD_INDEX" >> $GITHUB_OUTPUT
          # echo "shardIndex=${{ format('[1, {0}]', inputs.PARALLEL_TESTS) }}" >> $GITHUB_OUTPUT
          echo "shardTotal=${{ format('[{0}]', inputs.PARALLEL_TESTS) }}" >> $GITHUB_OUTPUT

  playwright:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        shardIndex: ${{ fromJSON(needs.matrix.outputs.shardIndex) }}
        shardTotal: ${{ fromJSON(needs.matrix.outputs.shardTotal) }}

    steps:
    - name: Download image
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      uses: actions/download-artifact@v4
      with:
        name: platform-ui.tar

    - name: Load image
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker load --input platform-ui.tar

    - name: Run container
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker run -d --name platform-ui -p 4100:443 -e PLATFORM_SERVER=${{ inputs.PLATFORM_SERVER }} platform-ui

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: PreCache
      run: npm version 0.0.0 --no-git-tag-version

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          /home/runner/.cache/Cypress
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ inputs.BROWSER }}

    - name: Run Playwright Tests
      working-directory: playwright
      run: npx playwright test --project="${{ inputs.PROJECT }}" --reporter=blob,line --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      env:
        PLATFORM_UI: ${{ inputs.PLATFORM_UI }}
        PLATFORM_USERNAME: ${{ inputs.PLATFORM_USERNAME != '' && inputs.PLATFORM_USERNAME || 'e2e' }}
        PLATFORM_PASSWORD: ${{ inputs.PLATFORM_PASSWORD != '' && inputs.PLATFORM_PASSWORD || secrets.PLATFORM_PASSWORD }}
        TAGS: ${{ inputs.TAGS }}
        NOT_TAGS: ${{ inputs.NOT_TAGS }}
        AWX_API_PREFIX: '/api/controller/v2'

    - name: Upload Playwright Blob Report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.BROWSER }}-blob-report-${{ matrix.shardIndex }}
        path: playwright/blob-report
        retention-days: 1

    - name: Upload Playwright Test Results to GitHub Actions Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-${{ inputs.BROWSER }}-${{ matrix.shardIndex }}
        path: playwright/test-results
        retention-days: 5
        overwrite: true
        if-no-files-found: ignore

    - name: Stop container
      if: ${{ inputs.PLATFORM_UI == 'https://localhost:4100' }}
      run: docker stop platform-ui

  playwright-report:
    name: Playwright report
    if: ${{ !cancelled() }}
    needs: [playwright]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: PreCache
      run: npm version 0.0.0 --no-git-tag-version

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          /home/runner/.cache/Cypress
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        pattern: ${{ inputs.BROWSER }}-blob-report-*
        merge-multiple: true

    - name: Merge Blob Reports
      working-directory: playwright
      run: |
        echo "Extracting blob reports..."
        cd ../all-blob-reports/
        counter=1
        for zip_file in *.zip; do
          unzip -q "$zip_file"
          # Rename the extracted report.jsonl to avoid conflicts
          if [ -f "report.jsonl" ]; then
            mv "report.jsonl" "report-shard-$counter.jsonl"
          fi
          counter=$((counter + 1))
        done
        cd ../playwright
        echo "Merging blob reports..."
        npx playwright merge-reports ../all-blob-reports --reporter json > results.json

    - uses: geekyeggo/delete-artifact@v5
      with:
          name: |
            ${{ inputs.BROWSER }}-blob-report-*

    - name: Generate Markdown Test Results
      working-directory: playwright
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        BROWSER: ${{ inputs.BROWSER }}
        PLATFORM_UI: ${{ inputs.PLATFORM_UI }}
        PLATFORM_SERVER: ${{ inputs.PLATFORM_SERVER }}
        PROJECT: ${{ inputs.PROJECT }}
        TAGS: ${{ inputs.TAGS }}
        NOT_TAGS: ${{ inputs.NOT_TAGS }}
        PARALLEL_TESTS: ${{ inputs.PARALLEL_TESTS }}
      run: |
        npm run markdown
        cat results.md >> $GITHUB_STEP_SUMMARY
  
    # - name: Merge into JUint Report
    #   run: npx playwright merge-reports --reporter junit ./all-blob-reports > ${{ inputs.BROWSER }}-junit.xml

    # - name: Upload JUint report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ inputs.BROWSER }}-junit-report
    #     path: ${{ inputs.BROWSER }}-junit.xml
    #     retention-days: 1

    # - name: Test Summary
    #   if: always()
    #   uses: test-summary/action@v2
    #   with:
    #     paths: ${{ inputs.BROWSER }}-junit.xml

    - name: Slack Success Notification
      if: ${{ inputs.SLACK_NOTIFICATION == true && success() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":playwright: *Playwright* `${{ inputs.PROJECT }}`: :done-circle-check: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Success>*"
                }
              }
            ]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Slack Failure Notification
      if: ${{ inputs.SLACK_NOTIFICATION == true && failure() }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":playwright: *Playwright* `${{ inputs.PROJECT }}`: :failed: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Failure>*"
                }
              }
            ]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
