name: UI E2E Image

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - '*'

jobs:
  ui-e2e-image:
    name: UI E2E Image
    uses: ./.github/workflows/image.yml
    with:
      docker-target: ui-e2e
      docker-image: quay.io/ansible/ui-e2e
      docker-publish: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
