name: Platfor Upgrades E2E

on:
  workflow_call:
    inputs:
      PLATFORM_SERVER:
        type: string
        required: true
      SKIP_JOB:
        type: boolean
        required: false
        default: false
      TAGS:
        type: string
        required: false
      CTRL_LDAP:
        type: boolean
        required: false
        default: false
      HUB_LDAP:
        type: boolean
        required: false
        default: false
      HUB_KEYCLOAK:
        type: boolean
        required: false
        default: false
      CTRL_OIDC:
        type: boolean
        required: false
        default: false
      CTRL_SAML:
        type: boolean
        required: false
        default: false
    secrets:
      PLATFORM_PASSWORD:
        required: true
      UPGRADES_PROJECT_ID:
        required: true
      UPGRADES_RECORD_KEY:
        required: true

jobs:
  platform-upgrades-e2e:
    name: Platform Upgrades E2E
    runs-on: ubuntu-latest
    steps:
      - name: Download container image
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/download-artifact@v4
        with:
          name: platform-ui.tar
      - name: Load container image
        if: ${{ !inputs.SKIP_JOB }}
        run: docker load --input platform-ui.tar
      - name: Checkout
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup node
        if: ${{ !inputs.SKIP_JOB }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: PreCache
        if: ${{ !inputs.SKIP_JOB }}
        run: npm version 0.0.0 --no-git-tag-version
      - name: Cache dependencies
        if: ${{ !inputs.SKIP_JOB }}
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            /home/runner/.cache/Cypress
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' && !inputs.SKIP_JOB
        run: npm ci
      - name: "Install python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install galaxykit
        run: |
          pip3 install ansible git+https://github.com/ansible/galaxykit.git@main
      - name: Strip trailing slash from PLATFORM_SERVER
        run: |
          echo "PLATFORM_SERVER=$(echo '${{ inputs.PLATFORM_SERVER }}' | sed 's:/*$::')" >> $GITHUB_ENV
      - name: Cypress
        if: ${{ !inputs.SKIP_JOB }}
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: docker run --rm -p 4100:443 -e PLATFORM_SERVER=${{ env.PLATFORM_SERVER }} platform-ui
          wait-on: 'https://localhost:4100'
          record: true
          parallel: false
          config-file: cypress.upgrades.config.ts
          tag: ${{ inputs.TAGS }}
        env:
          PLATFORM_SERVER: ${{ env.PLATFORM_SERVER }}
          PLATFORM_USERNAME: e2e
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          CYPRESS_PROJECT_ID: ${{ secrets.UPGRADES_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.UPGRADES_RECORD_KEY }}
          CYPRESS_AWX_API_PREFIX: /api/controller/v2
          CYPRESS_EDA_API_PREFIX: /api/eda/v1
          CYPRESS_BASE_URL: https://localhost:4100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          CYPRESS_LABELS: '!upstream'
          CTRL_LDAP: ${{ inputs.CTRL_LDAP }}
          HUB_LDAP: ${{ inputs.HUB_LDAP }}
          HUB_KEYCLOAK: ${{ inputs.HUB_KEYCLOAK }}
          CTRL_OIDC: ${{ inputs.CTRL_OIDC }}
          CTRL_SAML: ${{ inputs.CTRL_SAML }}
